eSalesBog/Controllers/ConsultantController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using static eSalesBog.Models.SalesViewModels;
using Common.Enums;
using Services.ServiceAbstract;
using Services.DTOs;

namespace eSalesBog.Controllers
{
    public class ConsultantController : Controller
    {

        private ISalesService _serviceClient;

        public ConsultantController(ISalesService serviceClient)
        {
            _serviceClient = serviceClient;
        }

        public ActionResult Index()
        {
            var dbConsultants = _serviceClient.GetConsultants();
            List<ConsultantViewModel> consultants = new List<ConsultantViewModel>();
            foreach (var item in dbConsultants)
            {
                consultants.Add(new ConsultantViewModel
                {
                    FirstName = item.FirstName,
                    LastName = item.LastName,
                    Gender = item.Gender,
                    BirthDate = item.BirthDate.Value.Date,
                    ID = item.ID,
                    PersonalNumber = item.PersonalNumber
                });
            }
            return View(consultants);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var dbConsultant = _serviceClient.GetConsultantById((int)id);
            ConsultantViewModel consultantDto = new ConsultantViewModel { FirstName = dbConsultant.FirstName, LastName = dbConsultant.LastName, PersonalNumber = dbConsultant.PersonalNumber };
            if (consultantDto == null)
            {
                return HttpNotFound();
            }
            return View(consultantDto);
        }

        public ActionResult Create()
        {
            LoadRecommenderConsultants(null);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,PersonalNumber,Gender,BirthDate,RecommenderConsultantID")] ConsultantViewModel consultant)
        {

            if (ModelState.IsValid)
            {
                if (_serviceClient.CheckIsConsultantRecommender(consultant.RecommenderConsultantID, consultant.PersonalNumber))
                {
                    ModelState.AddModelError(string.Empty, "არჩეული რეკომენდატორი არ შეიძლება იყოს იერარქიულად ამ კონსულტანტის რეკომენდატორი");
                }
                else
                {
                    ConsultantDto c = new ConsultantDto
                    {
                        FirstName = consultant.FirstName,
                        LastName = consultant.LastName,
                        BirthDate = consultant.BirthDate,
                        PersonalNumber = consultant.PersonalNumber,
                        Gender = consultant.Gender,
                        RecommenderConsultantID = consultant.RecommenderConsultantID
                    };
                    _serviceClient.CreateConsultant(c);

                    return RedirectToAction("Index");
                }
            }

            LoadRecommenderConsultants(null);
            return View(consultant);
        }

        public ActionResult Edit(int? id)
        {
            LoadRecommenderConsultants(id);

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var consultant = _serviceClient.GetConsultantById((int)id);
            ConsultantViewModel consultantModel = new ConsultantViewModel
            {
                ID=consultant.ID,
                FirstName = consultant.FirstName,
                LastName = consultant.LastName,
                BirthDate = consultant.BirthDate,
                PersonalNumber = consultant.PersonalNumber,
                Gender = consultant.Gender,
                RecommenderConsultantID = consultant.RecommenderConsultantID
            };
            if (consultantModel == null)
            {
                return HttpNotFound();
            }
            return View(consultantModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,PersonalNumber,Gender,BirthDate,RecommenderConsultantID")] ConsultantViewModel consultant)
        {
            if (ModelState.IsValid)
            {
                if (_serviceClient.CheckIsConsultantRecommender(consultant.RecommenderConsultantID, consultant.PersonalNumber))
                {
                    ModelState.AddModelError(string.Empty, "არჩეული რეკომენდატორი არ შეიძლება იყოს იერარქიულად ამ კონსულტანტის რეკომენდატორი");
                }
                else
                {
                    ConsultantDto c = new ConsultantDto
                    {
                        ID = consultant.ID,
                        FirstName = consultant.FirstName,
                        LastName = consultant.LastName,
                        BirthDate = consultant.BirthDate,
                        PersonalNumber = consultant.PersonalNumber,
                        Gender = consultant.Gender,
                        RecommenderConsultantID = consultant.RecommenderConsultantID
                    };
                    _serviceClient.EditConultant(c);
                    return RedirectToAction("Index");
                }
            }
            LoadRecommenderConsultants(null);
            return View(consultant);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var consultant = _serviceClient.GetConsultantById((int)id);
            ConsultantViewModel consultantModel = new ConsultantViewModel
            {
                FirstName = consultant.FirstName,
                LastName = consultant.LastName,
                BirthDate = consultant.BirthDate,
                PersonalNumber = consultant.PersonalNumber,
                Gender = consultant.Gender,
                RecommenderConsultantID = consultant.RecommenderConsultantID
            };

            if (consultantModel == null)
            {
                return HttpNotFound();
            }
            return View(consultantModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _serviceClient.DeleteConsultant(id);
            return RedirectToAction("Index");
        }


        public void LoadRecommenderConsultants(int? id)
        {
            var dbConsultants = _serviceClient.GetConsultants();

            List<SelectListItem> consultants = new List<SelectListItem>();
            foreach (var item in dbConsultants)
            {
                consultants.Add(new SelectListItem
                {
                    Value = item.ID.ToString(),
                    Text = item.PersonalNumber + " " + item.FirstName + " " + item.LastName
                });
            }
            ViewData["RecommenderConsultants"] = consultants;

        }
    }
}

eSalesBog/Views/Consultant/Create.cshtml
@model eSalesBog.Models.SalesViewModels.ConsultantViewModel

@{
    ViewBag.Title = "ახალი";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonalNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonalNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonalNumber, "", new { @class = "text-danger" })
            </div>
        </div>      

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => Model.Gender, EnumHelper.GetSelectList(typeof(Common.Enums.GenderEnum)), "-- აირჩიეთ --", new { @class = "form-control" })
              
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.BirthDate, new {  @class = "form-control datepicker" })
               
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger " })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecommenderConsultantID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">               

                @*@Html.DropDownListFor(Model => Model.RecommenderConsultantID, new SelectList(Model.RecommenderConsultant, "ID", "PersonalNumber"), "-- აირჩიეთ --", new { @class = "form-control" })*@
                @Html.DropDownListFor(Model => Model.RecommenderConsultantID, (List<SelectListItem>)ViewData["RecommenderConsultants"], "-- აირჩიეთ --", new { @class = "form-control" })

              
                    @*@Html.ValidationMessageFor(model => model.RecommenderConsultantID, "", new { @class = "text-danger" })*@
</div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="შენახვა" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("სიაზე დაბრუნება", "Index")
</div>

@section scripts{

    <script src="~/Scripts/js/consultants.js"></script>

}

eSalesBog/Views/Consultant/Delete.cshtml
@model eSalesBog.Models.SalesViewModels.ConsultantViewModel

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h3>ნამდვილად გსურთ წაშლა?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonalNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonalNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecommenderConsultantID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecommenderConsultantID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="წაშლა" class="btn btn-default" /> |
            @Html.ActionLink("სიაზე დაბრუნება", "Index")
        </div>
    }
</div>

eSalesBog/Views/Consultant/Details.cshtml
@model eSalesBog.Models.SalesViewModels.ConsultantViewModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>დეტალები</h3>

<div>
   
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PersonalNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PersonalNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RecommenderConsultantID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RecommenderConsultantID)
        </dd>

    </dl>
</div>
<p>
 
    @Html.ActionLink("სიაზე დაბრუნება", "Index")
</p>

eSalesBog/Views/Consultant/Edit.cshtml
@model eSalesBog.Models.SalesViewModels.ConsultantViewModel

@{
    ViewBag.Title = "რედაქტირება";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>რედაქტირება</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PersonalNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PersonalNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PersonalNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => Model.Gender, EnumHelper.GetSelectList(typeof(Common.Enums.GenderEnum)), "-- აირჩიეთ --", new { @class = "form-control" })

            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.BirthDate, new { @class = "form-control datepicker" })

                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger " })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RecommenderConsultantID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(m => m.RecommenderConsultantID, (List<SelectListItem>)ViewData["RecommenderConsultants"], "-არჩევა-", new { @class = "form-control" })


                @Html.ValidationMessageFor(model => model.RecommenderConsultantID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="შენახვა" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("სიაზე დაბრუნება", "Index")
</div>

eSalesBog/Views/Consultant/Index.cshtml
@model List<eSalesBog.Models.SalesViewModels.ConsultantViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>კონსულტანტები</h3>

<p>
    <a class="btn btn-white btn-sm" href="@Url.Action("Create", "Consultant")">
        <i class="fa fa-plus"></i>&nbsp;ახლის დამატება
    </a>
</p>
<table class="table table-hover table-responsive">
    <tr>
        <th>
            სახელი
        </th>
        <th>
            გვარი
        </th>
        <th>
            პირადი ნომერი
        </th>
        <th>
            სქესი
        </th>
        <th>
            დაბადების თარიღი
        </th>
        <th>

        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PersonalNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate.Value.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RecommenderConsultantID)
            </td>
            <td>
                <a class="btn btn-white btn-sm" href="@Url.Action("Edit", "Consultant", new { id = item.ID })">
                    <i class="fa fa-pencil"></i>&nbsp;რედაქტირება
                </a>
                |
                <a class="btn btn-white btn-sm" href="@Url.Action("Details", "Consultant", new { id = item.ID })">
                    <i class="fa fa-eye"></i>&nbsp;დათვალიერება
                </a>
                 |
                <a class="btn btn-white btn-sm" href="@Url.Action("Delete", "Consultant", new { id = item.ID })">
                    <i class="fa fa-trash"></i>&nbsp;წაშლა
                </a>
               
            </td>
        </tr>
    }

</table>